version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch
    ports:
      - 9200:9200
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - kibana:/usr/share/kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: 5

volumes:
  esdata:
  kibana:

# docker exec -it elasticsearch /usr/share/elasticsearch/bin/elasticsearch-reset-password -u elastic
# docker exec -it elasticsearch /usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token -s kibana
# search.max_async_search_response_size: 50mb
