FROM alpine
ENV PYTHONUNBUFFERED=1
RUN apk add --no-cache python3 \
  && if [ ! -e /usr/bin/python ]; then ln -sf python3 /usr/bin/python ; fi \
  && python3 -m ensurepip \
  && rm -r /usr/lib/python*/ensurepip \
  && rm -rf /etc/apk/cache

RUN pip3 install --no-cache --upgrade pip setuptools wheel\
  && if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi \
  && apk add ansible \
  && rm -rf /var/cache/* \
  && rm -rf /root/* \
  && rm -rf /etc/apk/cache
