# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  config.vm.provider 'virtualbox' do |vb|
    vb.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 1000 ]
  end
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  $num_instances = 3
  # curl https://discovery.etcd.io/new?size=3
  (1..$num_instances).each do |i|
    config.vm.define "node#{i}" do |node|
      # node.vm.box = "centos/7"
      node.vm.box = "ubuntu/focal64"
      node.vm.hostname = "node#{i}"
      ip = "10.0.0.#{i+100}"
      # node.vm.network "public_network", ip: ip, bridge: "en0: Wi-Fi (Wireless)"
      node.vm.network "private_network", ip: ip
      node.vm.provider "virtualbox" do |vb|
        vb.memory = "3072"
        vb.cpus = 1
        vb.name = "node#{i}"
      end
      # node.vm.provision "shell", path: "install.sh"#, args: [num_instances]
      node.vm.provision "shell", path: "install_ubuntu.sh"
    end
  end
  #config.vm.provision "shell", path: "running.sh"
end
