kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: local
networking:
  # apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
  # podSubnet: "10.254.0.0/16"
  # serviceSubnet: "10.96.0.0/12"
  # kubeProxyMode: "ipvs" # defaults to "iptables"
nodes:
- role: control-plane
  # add a mount from /path/to/my/files on the host to /files on the node
  extraMounts:
  - hostPath: /path/to/my/files
    containerPath: /files
    readOnly: true # default false
    selinuxRelabel: false # default false
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    listenAddress: "127.0.0.1" # default "0.0.0.0"
    protocol: TCP # one of TCP, UDP, SCTP
- role: worker
- role: worker
- role: worker