# rotate aws ecr login password
apiVersion: v1
kind: Secret
metadata:
  name: aws-ecr-secrets-helper
  namespace: default
stringData:
  AWS_SECRET_ACCESS_KEY: "xxxx"
  AWS_ACCESS_KEY_ID: "xxx"
  AWS_ACCOUNT: "xxx"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-ecr-configmap-helper
  namespace: default
data:
  AWS_REGION: "ap-northeast-1"
  DOCKER_SECRET_NAME: registrysecret
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: aws-ecr-cronjob-helper
  namespace: default
spec:
  schedule: "0 */10 * * *"
  successfulJobsHistoryLimit: 3
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: aws-ecr-serviceaccount
          containers:
          - name: aws-ecr-cronjob-helper
            image: odaniait/aws-kubectl:latest
            imagePullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: aws-ecr-secrets-helper
              - configMapRef:
                  name: aws-ecr-configmap-helper
            command:
              - /bin/sh
              - -c
              - |-
                ECR_TOKEN=`aws ecr get-login-password --region ${AWS_REGION}`
                NAMESPACE_NAME=default
                kubectl delete secret --ignore-not-found $DOCKER_SECRET_NAME -n $NAMESPACE_NAME
                kubectl create secret docker-registry $DOCKER_SECRET_NAME \
                --docker-server=https://${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com \
                --docker-username=AWS \
                --docker-password="${ECR_TOKEN}" \
                --namespace=$NAMESPACE_NAME
                echo "Secret was successfully updated at $(date)"
          restartPolicy: Never
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-ecr-serviceaccount
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: role-full-access-to-secrets
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["registrysecret"]
  verbs: ["delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aws-ecr-serviceaccount
  namespace: default
subjects:
- kind: ServiceAccount
  name: aws-ecr-serviceaccount
  namespace: default
  apiGroup: ""
roleRef:
  kind: Role
  name: role-full-access-to-secrets
  apiGroup: ""
